# Generated by Django 4.0.10 on 2023-04-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfKindergarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='действующий')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='действующий')),
                ('kindergarden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.listofkindergarden')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, upload_to='accommodation_img')),
                ('short_desc', models.TextField(blank=True, max_length=60, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('availability', models.PositiveIntegerField(verbose_name='свободных мест')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('group_desc', models.TextField(blank=True, max_length=60, verbose_name='описание группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.listofareas')),
                ('kindergarden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.listofkindergarden')),
            ],
        ),
    ]
